export const LOAD_MORE = "Load More";
export const SHOW_LESS = "Show Less";
export const PER_PAGE = 4;
export const TASK_ADDED_MESSAGE = "New Task Added";
export const EMPTY_TITLE_MESSAGE = "Please Enter the Task Title";
export const CREATE_CANCEL_MESSAGE = "Task Creating Cancelled";
export const EDIT_CANCEL_MESSAGE = "Task Editing Canceled";
export const TASK_DELETE_MESSAGE = "Task Deleted";
export const STATE_CHANGE_MESSAGE = "Task Completed";
export const EDIT_SUCCESS_MESSAGE = "Task Edited";
export const SEARCH_DATA_MESSAGE= "Search Data Shown"
